# Notebook: Análisis de datos financieros

**Descripción del flujo del notebook**

En este notebook se implementan dos funciones principales para trabajar con datos financieros de Bitcoin. El flujo es el siguiente:

    Obtener datos de Bitcoin desde Kraken:
    -Utilizamos la función get_BTC_data para descargar y estructurar datos históricos de Bitcoin desde la API de Kraken.
    Aplicar lógica de decisión con OpenAI:
    -La función calculate_metrics añade una columna con recomendaciones (Buy) basadas en datos históricos mediante la API de OpenAI.

In [ ]:
from APIS.Kraken_API import get_BTC_data
from APIS.Openai_API import calculate_metrics

 Esta celda llama a la API de Kraken y descarga los datos históricos de BTC en intervalos de 1 hora. Los datos incluyen columnas como open, high, low, close, vwap, volume, y Date.

In [ ]:
df = get_BTC_data()
df.head()

,open,high,low,close,vwap,volume,count,Date
0,68182.8,68186.7,68167.0,68170.8,68178.8,6.400930,455,2024-10-19 19:00:00
1,68170.9,68229.4,68170.8,68224.2,68215.4,5.438052,500,2024-10-19 20:00:00
2,68224.2,68329.9,68215.0,68215.0,68265.6,12.596959,653,2024-10-19 21:00:00
3,68215.1,68388.0,68214.8,68347.5,68262.6,8.256068,708,2024-10-19 22:00:00
4,68347.5,68375.0,68295.4,68374.9,68345.4,5.454873,641,2024-10-19 23:00:00

Esta celda llama a la API de OpenAI para analizar los datos descargados y añadir la columna Buy. Solo se utilizan las últimas 200 filas (df.iloc[-200:]) para mantener el análisis manejable.

In [3]:
df = calculate_metrics(df.iloc[-200:])
df.head()

                                                                               ```csv
open    high    low     close   vwap    volume       count Date                   Buy
79592.1 80000.0 79592.1 79920.6 79883.4 171.25598371 2469  2024-11-10 11:00:00  False
79920.6 80070.0 79388.0 79684.9 79702.1 256.3531017  2578  2024-11-10 12:00:00  False
79686.1 79899.0 79618.0 79779.6 79787.5 110.47021643 1692  2024-11-10 13:00:00  False
79779.5 80000.0 79271.7 79608.1 79632.3 250.98049465 2505  2024-11-10 14:00:00  False